drop table if exists person;
drop table if exists status;
drop table if exists task;
   
    create table person (
       id bigint generated by default as identity,
        name varchar(255),
        primary key (id)
    );
    
    create table status (
       id bigint generated by default as identity,
        description varchar(255),
        primary key (id)
    );
    
    create table task (
       id bigint generated by default as identity,
        active boolean,
        description varchar(255),
        title varchar(255),
        person_id bigint,
        status_id bigint,
        primary key (id)
    );
    
    
    alter table task 
       add constraint FK1b9x9tb4qrlrhnb6v2xes2792 
       foreign key (person_id) 
       references person;
       
    alter table task 
       add constraint FK9amdidv53i0hvjvnxkrup18t4 
       foreign key (status_id) 
       references status;
       
       insert into person (id, name) values (null, 'Erika');
       
       insert into person (id, name) values (null, 'Dante');
       
       insert into person (id, name) values (null, 'Mario');
       
       insert into status (id, description) values (null, 'nuevo');
       
       insert into status (id, description) values (null, 'activo');
       
       insert into status (id, description) values (null, 'bloqueado');
       
       insert into status (id, description) values (null, 'completado');
       
       commit;